### ISSUE TITLE
Same username

### ISSUE THREAD

**Issue by josephmiller2000** [ThPadelis/Chat.me#1]
Check the screenshot,
So any user can login with the same username? and pretend like the other users?
Fix it and make a pop up front login page to choose the login name instead of using the username in the chat screen near texting area.

![snap_2018 05 04_23h07m09s_001_](https://user-images.githubusercontent.com/24210340/39642706-2a0c26e2-4ff0-11e8-9bfa-71e8d9fa6039.png)

**Comment by ThPadelis** [comment]
Update the whole ui. I just need to fix the names as you said. Thanks for mentioning
